font_family      JetBrainsMono Nerd Font Mono
font_size        12

background        #12140d
foreground        #e3e3d7
cursor            #bbcf82
selection_background #3d4c0e

color0            #1f2019
color8            #292b23
color1            #ffb4ab
color9            #93000a
color2            #204e47
color10           #bcece2
color3            #434931
color11           #dfe6c4
color4            #bbcf82
color12           #3d4c0e
color5            #c3caa9
color13           #a1d0c6
color6            #a1d0c6
color14           #bcece2
color7            #e3e3d7
color15           #909284

background_opacity 0.65
dynamic_background_opacity yes
macos_option_as_alt yes

shell_integration enabled

mark1_foreground #bbcf82
mark1_background #1f2019
mark2_foreground #a1d0c6
mark2_background #292b23

tab_bar_style     powerline
window_padding_width 8

map ctrl+shift+t  new_tab
map ctrl+shift+Enter new_window
map ctrl+shift+z scroll_to_prompt -1
map ctrl+shift+x scroll_to_prompt 1
