font_family      JetBrainsMono Nerd Font Mono
font_size        12

background        #141318
foreground        #e5e1e9
cursor            #c9beff
selection_background #483f77

color0            #201f25
color8            #2b292f
color1            #ffb4ab
color9            #93000a
color2            #623b4c
color10           #ffd8e6
color3            #484459
color11           #e6dff9
color4            #c9beff
color12           #483f77
color5            #c9c3dc
color13           #edb8cd
color6            #edb8cd
color14           #ffd8e6
color7            #e5e1e9
color15           #938f99

background_opacity 0.65
dynamic_background_opacity yes
macos_option_as_alt yes

shell_integration enabled

mark1_foreground #c9beff
mark1_background #201f25
mark2_foreground #edb8cd
mark2_background #2b292f

tab_bar_style     powerline
window_padding_width 8

map ctrl+shift+t  new_tab
map ctrl+shift+Enter new_window
map ctrl+shift+z scroll_to_prompt -1
map ctrl+shift+x scroll_to_prompt 1
