font_family      JetBrainsMono Nerd Font Mono
font_size        12

background        #131318
foreground        #e5e1e9
cursor            #c6bfff
selection_background #454077

color0            #201f25
color8            #2a292f
color1            #ffb4ab
color9            #93000a
color2            #613b4e
color10           #ffd8e8
color3            #474459
color11           #e4dff9
color4            #c6bfff
color12           #454077
color5            #c8c3dc
color13           #ecb8cf
color6            #ecb8cf
color14           #ffd8e8
color7            #e5e1e9
color15           #928f99

background_opacity 0.65
dynamic_background_opacity yes
macos_option_as_alt yes

shell_integration enabled

mark1_foreground #c6bfff
mark1_background #201f25
mark2_foreground #ecb8cf
mark2_background #2a292f

tab_bar_style     powerline
window_padding_width 8

map ctrl+shift+t  new_tab
map ctrl+shift+Enter new_window
map ctrl+shift+z scroll_to_prompt -1
map ctrl+shift+x scroll_to_prompt 1
