-- Autogenerated by matugen - do not edit directly
-- Template: ~/.config/matugen/templates/matugen-colors.lua
return {
  surface = "#12140d",
  on_surface = "#e3e3d7",
  surface_container = "#1f2019",
  surface_container_high = "#292b23",
  primary = "#bbcf82",
  primary_container = "#3d4c0e",
  secondary = "#c3caa9",
  secondary_container = "#434931",
  tertiary = "#a1d0c6",
  tertiary_container = "#204e47",
  error = "#ffb4ab",
  outline = "#909284",
}
