-- Autogenerated by matugen - do not edit directly
-- Template: ~/.config/matugen/templates/matugen-colors.lua
return {
  surface = "#141318",
  on_surface = "#e5e1e9",
  surface_container = "#201f25",
  surface_container_high = "#2b292f",
  primary = "#c9beff",
  primary_container = "#483f77",
  secondary = "#c9c3dc",
  secondary_container = "#484459",
  tertiary = "#edb8cd",
  tertiary_container = "#623b4c",
  error = "#ffb4ab",
  outline = "#938f99",
}
