[config]

[templates.colors]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/colors/colors.css'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.cava]
input_path = '~/.config/matugen/templates/cava'
output_path = '~/.config/cava/config'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/kitty.conf'

[templates.nvim]
input_path = '~/.config/matugen/templates/matugen-colors.lua'
output_path = '~/.config/nvim/lua/config/matugen_colors.lua'

