pulse.rules = [
    {
        matches = [
            {
                node.name = "audio-src"
            }
            {
                media.name = "audio-src"
            }
            {
                application.process.binary = "spotify"
            }
        ]
        actions = {
            update-props = {
                application.name = "Spotify"
                application.icon_name = "spotify"
                application.process.binary = "spotify"
                node.description = "Spotify"
            }
        }
    }
]
