monitor.alsa.rules = [
  {
    matches = [
      {
        "node.name" = "audio-src"
      }
    ]
    actions = {
      update-props = {
        "application.name" = "Spotify"
        "application.icon_name" = "spotify"
        "application.process.binary" = "spotify"
        "node.description" = "Spotify"
      }
    }
  }
]
