-- Autogenerated by matugen - do not edit directly
-- Template: ~/.config/matugen/templates/matugen-colors.lua
return {
  surface = "{{colors.surface.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  surface_container = "{{colors.surface_container.default.hex}}",
  surface_container_high = "{{colors.surface_container_high.default.hex}}",
  primary = "{{colors.primary.default.hex}}",
  primary_container = "{{colors.primary_container.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  secondary_container = "{{colors.secondary_container.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  tertiary_container = "{{colors.tertiary_container.default.hex}}",
  error = "{{colors.error.default.hex}}",
  outline = "{{colors.outline.default.hex}}",
}
